name: "Deploy Web Project to Prod"
description: "Deploy Web Project to Prod using the action in the monorepo"
runs:
  using: "composite"
  steps:
    - name: Install
      run: pnpm install

    - name: Build
      run: pnpm build
